"""Stupid REPL for C/C++."""

import argparse
import os
import platform
import shlex
import shutil
import subprocess
import sys
import tempfile

try:
    # Just importing this is enough.
    import readline     # noqa
except ImportError:
    pass


SOURCE_TEMPLATE = """\
/* This is a source file generated by %(this file)s. */

%(directives)s

int main(int argc, char **argv)
{
    %(source)s
    return 0;
}
"""


def run(command, **kwargs):
    status = subprocess.call(command, **kwargs)
    if status != 0:
        print(' '.join(map(shlex.quote, command)), "exited with status",
              status, file=sys.stderr)
    return status


def main():
    cc = os.environ.get('CC', 'cc')
    cflags = os.environ.get('CFLAGS', '')
    libs = os.environ.get('LIBS', '')

    directives = ''
    tempdir = tempfile.mkdtemp()
    sources = []
    nested_level = 0

    print("Welcome to this program! Type HELP to get started.")
    try:
        while True:
            try:
                source = input('>>> ')
                while source.endswith('\\'):
                    source = source[:-1] + input('... ')
            except KeyboardInterrupt:
                print("\nInterrupt, type Ctrl-D to quit.")
                continue
            except EOFError:
                print()
                return

            if source.strip() == 'HELP':
                print("Example:")
                print()
                print('    >>> #include <stdio.h>')
                print(r'    >>> printf("Hello World!\n");')
                print('    Hello World!')
                print()
                continue

            if source.lstrip().startswith('#'):
                directives += source
                directives += '\n'
                continue
            
            if '{' in source: nested_level += 1
            if '}' in source: nested_level -= 1
            sources.append(source)
            if nested_level == 0:
                ready_source = SOURCE_TEMPLATE % {
                    'source': ''.join(sources),
                    'directives': directives,
                    'this file': __file__}
                with open(os.path.join(tempdir, 'source.c'), 'w') as f:
                    f.write(ready_source)

                cc_args = ([cc] + shlex.split(cflags) + ['source.c']
                           + shlex.split(libs))
                if run(cc_args, cwd=tempdir) == 0:
                    if platform.system() == 'Windows':
                        run([os.path.join(tempdir, 'a.exe')])
                    else:
                        run([os.path.join(tempdir, 'a.out')])

    finally:
        shutil.rmtree(tempdir)


if __name__ == '__main__':
    main()
